library(shiny)
library(ggplot2)
library(dplyr)
library(plotly)
library(stringr)


shinyServer(function(input, output) {
  dataR <- read.csv(file = "rev.csv" , sep = ",", stringsAsFactors = TRUE)
  output$boxPlot <- renderPlotly({
    if (is.null(input$RevYear)) {
      return()
    }
    colours <- c("Female" = "lightpink", "Male" = "lightblue1") 
    rev_year <- filter(dataR,Year == input$RevYear)
    if(length(rev_year) != 0) {
    ggplot(rev_year, aes(x = Gender, y = Revenue, fill = Gender)) +
      geom_boxplot() + ylim(0, 3) + scale_fill_manual(values = colours) +
      ggtitle(paste0("Revenue Generated by Male-Led Movies Versus Female-Led Movies in ", input$RevYear))
    } else {
      return("There is no data available")
    }
      })
  
})