library(R.utils)
library(ggplot2)
library(dplyr)
library(plotly)
library(shiny)
library(shinythemes)

source("ratings_data.R")

my_ui <- fluidPage(
  theme = shinytheme("superhero"),
  tabsetPanel(
    tabPanel(
      "Home",
      titlePanel("The Gender Gap in Representation in Movies Through the Years (1931 - 2015)"),
      h2("Goal"),
      p("The purpose of this project is to really draw attention to the blatant unequal representation between genders in movies. 
                     We are going to be looking at the number of roles of each gender, the number of words each gender 
                     gets to say, as well as the ratings and revenue of movies with a male or female lead. 
                     You can also select an individual movie and then see the gender representation by the number of words male and female characters say.
                    We define a female-led film, as one where the character with the most words spoken is a female. A male-led film is 
                    a movie where the character with the most words spoke in a male.
                    We would also like to point that we recognize
                     that gender is not binary, but the data available to us only male and female genders."),
      h2("Questions to Think About"),
      p("What is the gender representation of my favorite film? Can it be improved?"),
      p("How has gender representation changed throughout time? Is the disparity shrinking?"),
      p("How does gender representation impact revenue and ratings"),
      p("What can be do to address this disparity in media?"),
      h2("Dataset"),
      p(em("Our dataset is a combination of one from IMDB and another from  Matthew Daniel's Repository, 
                which explored the number of words said by male and females in individual movies.  We had information such as movie title, 
                release date, IMDB rating, characters, character gender, character age, number of words a character spoke,  
                and revenue generated by the movie."))
    ),
    tabPanel(
      "Select A Movie", titlePanel("Gender Representation by Movies"),
      p("Type in a movie that you are interested in learning about. Compare the 
                number of words said by females characters to male characters"),
      sidebarLayout(
        sidebarPanel(
          selectizeInput("movie", "Search for a movie:", choices = NULL, multiple = FALSE, uiOutput("movieSearch"))
        ),
        mainPanel(
          plotlyOutput("charwords"), p(textOutput("sumStatement"))
        )
      ),
      h3("Total there are 18821 characters and 17367445 spoken in this dataset. There are 5657 
              female characters that say a total of 4891976 words. There are 13161 male characters 
              that say a total of 12474717 words. Male characters make up around 70% of the characters and 
               say 72% of the words. Female characters make up 30% of the characters and say 28% of the words")
    ),
    tabPanel(
      "Yearly Comparision",
      titlePanel("Comparision of Gender Disparity Through the Years"),
      p(em("Select the IMDB button to rank films by IMDB ratings or Select Revenue to rank by the movie's 
                  gross. The movies displayed are the top 15 by IMDB rating or Revenue.
                  Select a year with the slider or click on the play 
                  button to see a time lapse of gender representation starting from your selected year.")),
      mainPanel(plotlyOutput("plot", height = 600, width = 850), p(textOutput("summary"))),
      sidebarPanel(
        sliderInput("Year", h2("Select a Year"),
          min = 1971, max = 2015, value = 1971, sep = "",
          step = 1, animate = animationOptions(interval = 1000, loop = FALSE)
        ),
        radioButtons(
          "Rankings", h2("Select to Rank by IMDB Rating or Revenue"),
          c("IMDB", "Revenue")
        ),
        p(em("Note: Visualization starts at 1971 instead of 1931, due to lack of data between 1931-1971. 
                      Some years may not have 15 movies, due to the dataset not containing 15 movies for that
                      specific year"))
      ), h3("There are 248 female-led movies overall. 1 of 
                    these movies was in the Top 15 (by IMDB) and 3 movies were in the Top 15 
                    (by revenue).The movie with the biggest gender
                    disparity was Casino with a difference of 48210 words between male 
                    and female characters.")
    ),
    tabPanel(
      "IMDB Rankings Vs. Gender of Lead",
      titlePanel(h1(strong("IMDB Movie Ratings Over Time"))),

      p(em("IMDB ratings are based upon the general population's vote.  This visualization compares
                 the median IMDB movie rating for movies with a female lead versus movies with a male lead
                 for each decade.  You may select which decade(s) to view and compare.")),

      sidebarLayout(
        sidebarPanel(
          checkboxGroupInput("checked_decade",
            label = h3("Decades:"),
            choices = list(
              "1930s" = "1930s", "1940s" = "1940s", "1950s" = "1950s",
              "1960s" = "1960s", "1970s" = "1970s", "1980s" = "1980s",
              "1990s" = "1990s", "2000s" = "2000s", "2010s" = "2010s"
            ),
            selected = c(
              "1930s", "1940s", "1950s", "1960s", "1970s", "1980s",
              "1990s", "2000s", "2010s"
            )
          ),
          hr(),
          fluidRow(column(3, verbatimTextOutput("checked_decade")))
        ),
        mainPanel(
          strong("Bar Graph"),
          p(em("There are a total of ", num_movies_female, "movies with a female
                             lead and ", num_movies_male, "movies with a male lead. We have movies ranging from ", start_date_words, "to ", end_date_words)),
          plotlyOutput("mybargraph")
        )
      ), h2("Analysis"), p(em("Looking at the graphs over the years, we can see that the IMDB rankings 
                                      for female dominated movies seem to be similar or in some cases better
                                      than male dominated movies. Therefore, the argument that female movies
                                      aren't well recieved by auidences, seems not to be the case here. 
                                      If female-led movies are as well recieved as male-led movies,then why is there such a
                                      lack of female representation in movies?"))
    ),
    tabPanel(
      "Revenue vs. Gender of the Lead",

      titlePanel("Revenue vs. Gender of the Lead"),
      p(em("Compare the Revenue generated by Male-Led and Female-Led Movies 
              Through the years. Click on autoscale button to autoscale the data.
              Scroll over the data to see more information on the range of the movie, 
              including 1st Quartile, Mean, 3rd Quartile, endpoints, and outliers. 
              Note: The Revenue is in Billions of US Dollars
              ")),
      mainPanel(plotlyOutput("boxPlot")),
      sidebarPanel(
        sliderInput("RevYear", h2("Select a Year"),
          min = 1931, max = 2015, value = 1971, sep = "",
          step = 1
        )
      ), h1("Analysis"), p("Looking at the data, it is clear that male-dominated movies 
                                   seem to make more revenue than female-dominated movies. We think this 
                                 might be due to the sheer difference between the amount of female-led 
                                 versus male-dominated movies, which would explain the usually larger range of 
                                of revenue. It could reveal deeper biases against
                                female-led movies, as when we compare revenue to gender, we see that they are just as 
                                well-received as male-led movies by rankings, but this requires 
                                further analysis and research to back such a claim")
    ),
    tabPanel(
      "Conclusion", titlePanel(h1("Overall Analysis")),
      p("Through our visualizations to becomes clear that there is gender disparity between males and females in movies. A further analysis seems to show that while this difference does exist, the arguments for why it exists does not make sense. 
        A common argument is that female-led films are received less positively by the audience, but looking at the data male-led movies and female-led movies receive similar scores on IMDB.
    While male-led movies do make more money at the box office, there exists a substantial gap between the number of  
male-led and female-led movies. But, if male-led and female-led movies recieve similar reception by the audience 
why is that male-led movies make more money? Do more people go to male-led movies than female-led movies? 
Could it be that male-led movies have both a female and male audience, but female-led 
movies only have a female audience? We can't answer that question with our current analysis and data, but 
           our work reveals that there is a clear difference between gender representation in movies. Understanding 
           and recognizing that there is a problem is only the first step in finding solutions"), h2("Future Explorations"),
      p("To further explore this topic, it would be necessary to look at who is making the 
movies. What are the genders of the producers, screenwriters, and directors?
How is that correlated to the representation that ends up in the film? Furthermore, we could look at 
film goers and learn about the gender make-up of a film's audience and what they think of the movie. 
We can try to determine maybe if there is a bias for or against female-led films, based on this data.")
    )
  )
)
shinyUI(my_ui)